### ISSUE TITLE
Plans TODO

### ISSUE THREAD

**Issue by kyleslie2** [kyleslie2/juniper-renos#1]
- [ ] Optimize images
- [ ] Add new logo
- [ ] add new favicon
- [ ] get full-width images working with background scroll effect
- [ ] change colours
- [ ] remove un-needed sections
- [ ] change social media links
- [ ] transfer hosting to hannah/ ethan
